package UIFrames;
/*
 * @author Ronaldo Vindas 2018238697
 */
public class Login_Menu extends javax.swing.JFrame {

    public Login_Menu() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        Register_button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 50, 50));

        Register_button.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        Register_button.setForeground(new java.awt.Color(255, 255, 255));
        Register_button.setText("Not a User? Register");
        Register_button.setBorderPainted(false);
        Register_button.setContentAreaFilled(false);
        Register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Register_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_buttonMouseExited(evt);
            }
        });
        Register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, 280, 30));

        Login_Button.setBackground(new java.awt.Color(181, 212, 197));
        Login_Button.setFont(new java.awt.Font("Levenim MT", 1, 18)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(0, 0, 0));
        Login_Button.setText("LOG IN");
        Login_Button.setBorder(null);
        Login_Button.setBorderPainted(false);
        Login_Button.setContentAreaFilled(false);
        Login_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Login_Button.setFocusCycleRoot(true);
        Login_Button.setFocusPainted(false);
        Login_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login_Button.setName(""); // NOI18N
        Login_Button.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Login_ButtonFocusGained(evt);
            }
        });
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseExited(evt);
            }
        });
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Final Login Window 2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_buttonActionPerformed
        Register_Window result = new Register_Window();
        result.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Register_buttonActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        Login_Window result = new Login_Window();
        result.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Login_ButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_ButtonFocusGained

    }//GEN-LAST:event_Login_ButtonFocusGained

    private void Login_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseEntered
        //Log_In_Panel.setBackground(new java.awt.Color(44,168,109));
        Login_Button.setForeground(new java.awt.Color(19,79,139));
    }//GEN-LAST:event_Login_ButtonMouseEntered

    private void Login_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseExited
        //Log_In_Panel.setBackground(new java.awt.Color(181,212,197));
        Login_Button.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_Login_ButtonMouseExited

    private void Register_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_buttonMouseEntered
        Register_button.setForeground(new java.awt.Color(0,102,204));
    }//GEN-LAST:event_Register_buttonMouseEntered

    private void Register_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_buttonMouseExited
        Register_button.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Register_buttonMouseExited

    private void Login_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseClicked
        
    }//GEN-LAST:event_Login_ButtonMouseClicked

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton Login_Button;
    private javax.swing.JButton Register_button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
